// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `dbexample.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package dbexample;

public final class DatabasePrxHelper extends Ice.ObjectPrxHelperBase implements DatabasePrx
{
    private static final String __retrieve_name = "retrieve";

    public String retrieve(int key)
        throws NoSuchEntryException
    {
        return retrieve(key, null, false);
    }

    public String retrieve(int key, java.util.Map<String, String> __ctx)
        throws NoSuchEntryException
    {
        return retrieve(key, __ctx, true);
    }

    private String retrieve(int key, java.util.Map<String, String> __ctx, boolean __explicitCtx)
        throws NoSuchEntryException
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "retrieve", __ctx);
        int __cnt = 0;
        try
        {
            while(true)
            {
                Ice._ObjectDel __delBase = null;
                try
                {
                    __checkTwowayOnly("retrieve");
                    __delBase = __getDelegate(false);
                    _DatabaseDel __del = (_DatabaseDel)__delBase;
                    return __del.retrieve(key, __ctx, __observer);
                }
                catch(IceInternal.LocalExceptionWrapper __ex)
                {
                    __handleExceptionWrapper(__delBase, __ex, __observer);
                }
                catch(Ice.LocalException __ex)
                {
                    __cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
                }
            }
        }
        finally
        {
            if(__observer != null)
            {
                __observer.detach();
            }
        }
    }

    public Ice.AsyncResult begin_retrieve(int key)
    {
        return begin_retrieve(key, null, false, null);
    }

    public Ice.AsyncResult begin_retrieve(int key, java.util.Map<String, String> __ctx)
    {
        return begin_retrieve(key, __ctx, true, null);
    }

    public Ice.AsyncResult begin_retrieve(int key, Ice.Callback __cb)
    {
        return begin_retrieve(key, null, false, __cb);
    }

    public Ice.AsyncResult begin_retrieve(int key, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_retrieve(key, __ctx, true, __cb);
    }

    public Ice.AsyncResult begin_retrieve(int key, Callback_Database_retrieve __cb)
    {
        return begin_retrieve(key, null, false, __cb);
    }

    public Ice.AsyncResult begin_retrieve(int key, java.util.Map<String, String> __ctx, Callback_Database_retrieve __cb)
    {
        return begin_retrieve(key, __ctx, true, __cb);
    }

    private Ice.AsyncResult begin_retrieve(int key, java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__retrieve_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __retrieve_name, __cb);
        try
        {
            __result.__prepare(__retrieve_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeInt(key);
            __result.__endWriteParams();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public String end_retrieve(Ice.AsyncResult __result)
        throws NoSuchEntryException
    {
        Ice.AsyncResult.__check(__result, this, __retrieve_name);
        boolean __ok = __result.__wait();
        try
        {
            if(!__ok)
            {
                try
                {
                    __result.__throwUserException();
                }
                catch(NoSuchEntryException __ex)
                {
                    throw __ex;
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.__startReadParams();
            String __ret;
            __ret = __is.readString();
            __result.__endReadParams();
            return __ret;
        }
        catch(Ice.LocalException ex)
        {
            Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
            if(__obsv != null)
            {
                __obsv.failed(ex.ice_name());
            }
            throw ex;
        }
    }

    public static DatabasePrx checkedCast(Ice.ObjectPrx __obj)
    {
        DatabasePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof DatabasePrx)
            {
                __d = (DatabasePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId()))
                {
                    DatabasePrxHelper __h = new DatabasePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static DatabasePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        DatabasePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof DatabasePrx)
            {
                __d = (DatabasePrx)__obj;
            }
            else
            {
                if(__obj.ice_isA(ice_staticId(), __ctx))
                {
                    DatabasePrxHelper __h = new DatabasePrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static DatabasePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        DatabasePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId()))
                {
                    DatabasePrxHelper __h = new DatabasePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static DatabasePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        DatabasePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA(ice_staticId(), __ctx))
                {
                    DatabasePrxHelper __h = new DatabasePrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static DatabasePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        DatabasePrx __d = null;
        if(__obj != null)
        {
            if(__obj instanceof DatabasePrx)
            {
                __d = (DatabasePrx)__obj;
            }
            else
            {
                DatabasePrxHelper __h = new DatabasePrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static DatabasePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        DatabasePrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            DatabasePrxHelper __h = new DatabasePrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::dbexample::Database"
    };

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected Ice._ObjectDelM __createDelegateM()
    {
        return new _DatabaseDelM();
    }

    protected Ice._ObjectDelD __createDelegateD()
    {
        return new _DatabaseDelD();
    }

    public static void __write(IceInternal.BasicStream __os, DatabasePrx v)
    {
        __os.writeProxy(v);
    }

    public static DatabasePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            DatabasePrxHelper result = new DatabasePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
