// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `dbexample.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package dbexample;

public interface DatabasePrx extends Ice.ObjectPrx
{
    public String retrieve(int key)
        throws NoSuchEntryException;

    public String retrieve(int key, java.util.Map<String, String> __ctx)
        throws NoSuchEntryException;

    public Ice.AsyncResult begin_retrieve(int key);

    public Ice.AsyncResult begin_retrieve(int key, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_retrieve(int key, Ice.Callback __cb);

    public Ice.AsyncResult begin_retrieve(int key, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_retrieve(int key, Callback_Database_retrieve __cb);

    public Ice.AsyncResult begin_retrieve(int key, java.util.Map<String, String> __ctx, Callback_Database_retrieve __cb);

    public String end_retrieve(Ice.AsyncResult __result)
        throws NoSuchEntryException;
}
